import '../styles/globals.css';
import type { Metadata } from 'next';
import { Onest } from 'next/font/google';
import Header from '@/components/header';
import MarginWidthWrapper from '@/components/margin-width-wrapper';
import PageWrapper from '@/components/page-wrapper';
import SideNav from '@/components/side-nav';
import { BottomNav } from '@/components/bottom-nav';
import { premiumUser } from "@/lib/mockData"; 

const inter = Onest({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'SugarLab',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const user = premiumUser;
  return (
    <html lang="en">
      <body className={`bg-[--color-background-primary] ${inter.className}`}>
        <div className="flex">
          <SideNav />
          <main className="flex-1">
            <MarginWidthWrapper>
              <Header />
              <PageWrapper>{children}</PageWrapper>
              <BottomNav 
              isPremium={user.isPremium}
              isLoggedIn={user.isLoggedIn}/>
            </MarginWidthWrapper>
          </main>
        </div>
      </body>
    </html>
  );
}